version: "3.9"

services:
  links_postgres:
    image: postgres:15
    container_name: links_postgres
    volumes:
      - ~/.pg/pg_data/links:/var/lib/postgresql/data
    env_file:
      - .env
  links_project:
    image: links:latest
    container_name: links_con
    depends_on:
      - links_postgres
    volumes:
      - static_volume:/home/static
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 links.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: links_nginx
    image: links_nginx
    volumes:
      - static_volume:/home/static
    depends_on:
      - links_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
