version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations 
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pg

  pg:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgres
    env_file:
      - .env

volumes:
  db_data: